{"name": "test_mul[-3-error]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == 'error'\n  - error", "trace": "self = <pytest_work_two.test_work_two.TestCalc object at 0x7fab58fc90f0>, a = '', b = 3, expecter = 'error', print_news = None\n\n    @pytest.mark.third\n    @pytest.mark.parametrize(\"a,b,expecter\", value['values_mul'])\n    def test_mul(self, a, b, expecter,print_news):\n        # 调用calculator中的div方法，将结果保存到result中\n        try:\n            result = self.calc.mul(a, b)\n            print(result)\n            # 将结果和预期值进行对比\n>           assert result == expecter\nE           AssertionError: assert '' == 'error'\nE             - error\n\ntest_work_two.py:88: AssertionError"}, "parameters": [{"name": "a", "value": "''"}, {"name": "b", "value": "3"}, {"name": "expecter", "value": "'error'"}], "start": 1615047945430, "stop": 1615047945435, "uuid": "b8997c21-d15f-4a5b-8c62-322b2f64cce8", "historyId": "1a88eccd5d2a29542de0e9d1f789d0dc", "testCaseId": "dfd43b0ac6a5f96435e6c73af9321ca7", "fullName": "test_work_two.TestCalc#test_mul", "labels": [{"name": "tag", "value": "third"}, {"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_work_two"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "192.168.0.102"}, {"name": "thread", "value": "4494-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work_two"}]}